cmake_minimum_required(VERSION 3.16)
project(cassini_audio LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(OPUS_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(OPUS_BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
add_subdirectory(${OPUS_SOURCE} opus)
add_library(cassini_opus SHARED opus-jni.cpp)
target_link_libraries(cassini_opus PRIVATE opus)
target_compile_features(cassini_opus PRIVATE cxx_std_17)
target_link_options(cassini_opus PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,--no-undefined" "-Wl,--exclude-libs,ALL")
